---
- name: Create GCE instance with Debian 10
  hosts: localhost
  gather_facts: no
  vars:
    gcp_project: vpn-server-sasp
    gcp_cred_kind: serviceaccount
    gcp_cred_file: /home/cheo/sergio/gce_sa_keys/ansible-sa.json
    zone: "us-central1-a"
    region: "us-central1"

  tasks:
    - name: create a disk
      gcp_compute_disk:
        name: "disk-instance"
        size_gb: 10
        source_image: "projects/debian-cloud/global/images/family/debian-10"
        #type: 'pd-ssd' // uncomment if you want to create a SSD disk. Default is HDD.
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: disk
    - name: create a address
      gcp_compute_address:
        name: "{{ zone }}-ip"
        region: "{{ region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: address
    - name: create a instance
      gcp_compute_instance:
        state: present
        name: docker_nginx 
        machine_type: f1-micro
        can_ip_forward: yes
        metadata:
          enable-oslogin: true
          #enable-guest-attributes: true
        disks:
          - auto_delete: true
            boot: true
            source: "{{ disk }}"
        network_interfaces:
          - network: null # use default
            access_configs:
              - name: "External NAT"
                nat_ip: "{{ address }}"
                type: "ONE_TO_ONE_NAT"
        tags:
          items:
            - http-server
            - https-server
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
      register: instance

  post_tasks:
    - name: Wait for SSH for instance
      wait_for: host={{ address.address }} port=22 delay=10 timeout=60
    - name: Save host data for first zone
      add_host: hostname={{ address.address }} groupname=gce_instances_ips

- name: Install & setup Docker, build nginx image and run container
  hosts: gce_instances_ips
  become: yes
  roles:
    - docker
    - nginx
